### ISSUE TITLE
Add list-group-item dynamically

### ISSUE THREAD

**Issue by icyrainz** [rickardn/listgroup.js#1]
Is there any chance that I could add a list-group-item dynamically later and still has the click-to-active feature of listgroup.js ?
I have a bootstrap modal that loads data dynamically and put into list-group-item but it seems do not have this click-to-active feature after adding the listgroup.js

**Comment by rickardn** [comment]
Sure. Adding new list-group-item's to an activated list-group should work fine. Maybe the list-group hasn't been activated? Just call `$('#new-list-group').listgroup()` after you've added it to the page (or loaded the modal).

**Comment by icyrainz** [comment]
Thanks !
