### ISSUE TITLE
Set options as selected when list item is clicked

### ISSUE THREAD

**Issue by tdxdave** [rickardn/listgroup.js#12]
Am I missing something here? Shouldn't the selected options be marked as selected in the hidden select  when the corresponding list items is clicked so the form can actually be submitted?

**Comment by rickardn** [comment]
Yes they should, see http://rickardn.github.io/listgroup.js/#select-elements

**Comment by tdxdave** [comment]
Ok then. I was not able to figure that out. The select did not change. I wrote some code to extract the values from the list-group-items instead. I am using an ajax submit anyway. I'll try to debug it later.
