### ISSUE TITLE
Ajax Content

### ISSUE THREAD

**Issue by rdehnhardt** [rickardn/listgroup.js#6]
Hello!

How do I link the plugin after the ajax return?

**Comment by rdehnhardt** [comment]
solved the problem using the code below!

```
n(function () {
        n(".list-group").listgroup()

        $(document).bind("ajaxComplete", function () {
            n(".list-group").listgroup()
        }).bind("ajaxStop", function () {
            n(".list-group").listgroup()
        }).bind("ajaxSuccess", function () {
            n(".list-group").listgroup()
        }).bind("ajaxError", function () {
            n(".list-group").listgroup()
        });
    })
```

I think it would be cool to deploy this update in the plugin!

**Comment by rickardn** [comment]
Hi!

Can you elaborate on what your problem is and what you're trying to accomplish?

**Comment by rdehnhardt** [comment]
Calling a listgroup by ajax the plugin was not executed! Because the elements do not exist on the screen!

Soon I did above fixes this problem!

**Comment by rickardn** [comment]
Hi!
I may be wrong but I don't think that behavior is necessary in the most common scenarios and thus shouldn't be part of the plugin. However, I think its useful to add it to the documentation, as an example how you could achieve something like that.
