### ISSUE TITLE
dynamically created list view

### ISSUE THREAD

**Issue by watherton** [rickardn/listgroup.js#7]
Hi, I have a ajax call, that builds a list group (UL) dynamically. When applying the built html to a div like:

$('#someDiv').html(dynamicHtml);

then this plugin does nothing. If i take the dynamic html and recreate as standard html then it works fine.

Any ideas?

**Comment by rickardn** [comment]
You need to call $('.listgroup').listgroup() again either in the ajax callback or for all ajax callbacks. See #6 for an example.

**Comment by watherton** [comment]
Thanks Rickardn, I shall give that a try.
