### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by ivankennethwang** [rickardn/listgroup.js#8]
Hi, can you add this as a bower dependency? Thanks.

**Comment by rickardn** [comment]
You're very much welcome to submit a pull request.

**Comment by holtkamp** [comment]
@eforbus seems to have created a `bower.json` file and [registered it](https://libraries.io/bower/listgroup.js). Maybe an idea to have to original branch registered?

@eforbus maybe you can provide the contribution as PR?
